version: '3.9'
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: site-mr486
    ports:
      - '2024:80'
    volumes:
      - ./www:/usr/local/apache2/htdocs